files:
  - source: /*.md
    translation: /Localization/%two_letters_code%/%original_file_name%
  - source: /res/values/*.xml
    translation: /res/values-%two_letters_code%/%file_name%_%two_letters_code%.xml
