files:
  - source: /*.po
    ignore:
      - /*_*.po
    translation: /%file_name%_%two_letters_code%.po
  - source: /res/values/*.xml
    translation: /res/valuestest-%two_letters_code%/%original_file_name%
